"""Draft (L1) — project-level shared process graph for autonomous discovery.

Records hypotheses, experiments, results, dead ends, decisions, and their
relationships.  All roles read/write through these functions; the MCP
registration layer in ``mcp_server.py`` wraps them as tools.

Environment:
    MINIONS_PROJECT_PORT — identifies the project.

Storage:
    project_{port}/branches/main/draft/draft.json — canonical graph state.
    project_{port}/branches/main/draft/journal.jsonl   — append-only mutation log.

The Draft and journal live inside the cross-role shared worktree
(``branches/main/`` on branch ``minionsos/project-{port}-shared``) so
Draft history is auditable in git. ``mos_draft_append`` and
``mos_draft_annotate`` write to the working tree only; commits happen
on a cron through ``mos_draft_commit_shared``, which is owned by Ethics
(the memory curator) and flushes the buffered Draft state via
``mos_publish_to_shared`` (single commit per cron tick, message
"ethics: draft flush <ts>").
"""

from __future__ import annotations

import logging
import os
import tempfile
from collections import defaultdict, deque
from contextvars import ContextVar
from pathlib import Path
from typing import Any, cast

# Import from modularized submodules
from minions.tools.draft_decay import mos_draft_decay_compute, DECAY_HALF_LIFE_DAYS
from minions.tools.draft_edges import create_edges
from minions.tools.draft_helpers import (
    append_journal,
    env_port as _env_port,
    env_role as _env_role,
    load_decay as _load_decay,
    load_draft as _load_draft,
    now_iso as _now_iso,
    save_draft as _save_draft,
    validate_confidence as _validate_confidence,
)
import minions.tools.draft_helpers as _draft_helpers
from minions.tools.draft_nodes import (
    CURATOR_MOTIF_REQUIRED_TYPES,
    DraftNodeType,
    DraftProvenance,
    DraftSupportStatus,
    MOTIF_KINDS,
    NODE_TYPES,
    PROVENANCES,
    SUPPORT_STATUSES,
    create_nodes,
    resolve_pending_plans,
)
from minions.tools.draft_query import (
    DraftQueryResult,
    mos_draft_communities,
    mos_draft_god_nodes,
    mos_draft_path,
    mos_draft_query,
    mos_draft_relevant,
    mos_draft_topic_index,
)
from minions.paths import project_shared_subdir
from minions.errors import DraftError

# Re-export path functions for test compatibility
from minions.paths import project_shared_draft_json


logger = logging.getLogger(__name__)

# Re-export internal helpers for test compatibility
from minions.tools.draft_helpers import (
    decay_path as _decay_path,
    draft_path as _draft_path,
    journal_path as _journal_path,
    load_draft as _load_draft,
    parse_iso as _parse_iso,
    save_draft as _save_draft,
)


# Re-export for backward compatibility
from minions.tools.draft_edges import EDGE_RELATIONS
from minions.tools.draft_nodes import TYPE_PREFIX

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

BOOK_STATUS_HOOK_STATUSES = frozenset({"verified", "refuted", "dead_end"})
_BOOK_STATUS_EVENT_TARGET: ContextVar[dict[str, Any] | None] = ContextVar(
    "_BOOK_STATUS_EVENT_TARGET",
    default=None,
)

# Claim-bearing node types
_CLAIM_NODE_TYPES = CURATOR_MOTIF_REQUIRED_TYPES


# ---------------------------------------------------------------------------
# Book status event emission
# ---------------------------------------------------------------------------

def _emit_book_status_event(
    port: int,
    node_id: str,
    new_status: str,
    annotator: str,
) -> None:
    target = _BOOK_STATUS_EVENT_TARGET.get()
    if target is None or target.get("id") != node_id:
        draft = _load_draft(port)
        target = next(
            (node for node in draft["nodes"] if node.get("id") == node_id),
            {},
        )
    node_text = str(target.get("text", ""))
    node_type = str(target.get("type", ""))
    date_updated = _now_iso()
    blob = "\n".join(
        [
            "---",
            "type: hypothesis_status",
            f"draft_node_id: {node_id}",
            f"new_status: {new_status}",
            f"annotator_role: {annotator}",
            f"date_updated: {date_updated}",
            "page_kind: status_update",
            "---",
            f"# Hypothesis status update: {node_id}",
            "",
            f"**Node**: {node_id} ({node_type})",
            f"**New status**: {new_status}",
            f"**Text**: {node_text[:300]}",
            f"**Annotator**: {annotator}",
            f"**When**: {date_updated}",
            "",
            "Auto-generated by Phase 7 Draft↔Book hook.",
            "",
        ]
    )
    temp_path: Path | None = None
    try:
        temp_dir = project_shared_subdir(port, "ethics") / ".draft-status-events"
        temp_dir.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile(
            "w",
            encoding="utf-8",
            delete=False,
            dir=temp_dir,
            prefix="draft-status-",
            suffix=".md",
        ) as temp_file:
            temp_file.write(blob)
            temp_path = Path(temp_file.name)

        from minions.tools.book import mos_book_ingest

        mos_book_ingest(
            src_path=str(temp_path),
            source_role="ethics",
            source_slug=(f"draft-status-{node_id.replace('-', '').lower()[:30]}-{new_status}"),
            title=f"Status update: {node_id} → {new_status}",
            port=port,
        )
    except Exception as exc:
        logger.warning(
            "book status event emission failed for node %s status %s: %s",
            node_id,
            new_status,
            exc,
        )
    finally:
        if temp_path is not None:
            try:
                temp_path.unlink(missing_ok=True)
            except OSError as exc:
                logger.warning("failed to remove book status temp file %s: %s", temp_path, exc)



# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def _role_unmarked_ratio(
    nodes: list[dict[str, Any]], author_role: str, *, min_nodes: int = 3
) -> float | None:
    """Fraction of a role's claim-bearing Draft nodes whose ``evidence_tag`` is empty.

    Pure (no I/O), so it is trivially unit-testable. Returns ``None`` when the
    role has fewer than ``min_nodes`` claim nodes (too little signal to report).

    This measures evidence-tag coverage where tags actually live — the Draft
    node ``evidence_tag`` field — unlike :func:`minions.tools.book._source_role_unmarked_ratio`,
    which scans Book *prose* pages that almost never carry inline markers and so
    returns ~1.0 for every role. A higher value here means *worse* coverage.
    """
    claims = [
        n
        for n in nodes
        if (n.get("author_role") or "").strip() == author_role
        and n.get("type") in _CLAIM_NODE_TYPES
    ]
    if len(claims) < min_nodes:
        return None
    unmarked = sum(1 for n in claims if not str(n.get("evidence_tag") or "").strip())
    return round(unmarked / len(claims), 3)



def mos_draft_unmarked_audit(threshold: float = 0.2) -> dict[str, Any]:
    """Per-role unmarked-claim ratio over Draft nodes; an Ethics-facing signal.

    Computes, for each authoring role, the fraction of its claim-bearing nodes
    (types ``result`` / ``decision`` / ``hypothesis`` / ``insight``) that carry
    no ``evidence_tag``, and flags roles whose ratio exceeds ``threshold``
    (default ``0.2``). Roles with too few claim nodes report ``None`` and are
    never flagged.

    **Advisory only.** This does not auto-trigger re-tagging or retraction and
    does not mutate the Draft — it surfaces a descriptive coverage signal for
    Ethics to adjudicate, consistent with the "evidence convention is cultural,
    not mechanical" contract in ``minions/roles/SYSTEM.md``. Whitelisted to
    Ethics + Gru.
    """
    port = _env_port()
    nodes = _load_draft(port)["nodes"]
    roles = sorted(
        {
            (n.get("author_role") or "").strip()
            for n in nodes
            if (n.get("author_role") or "").strip()
        }
    )
    per_role = {role: _role_unmarked_ratio(nodes, role) for role in roles}
    flagged = sorted(r for r, v in per_role.items() if v is not None and v > threshold)
    return {
        "threshold": threshold,
        "per_role_unmarked": per_role,
        "flagged_roles": flagged,
    }



def mos_draft_append(
    nodes: list[dict[str, Any]] | None = None,
    edges: list[dict[str, Any]] | None = None,
    resolves_pending: list[str] | None = None,
) -> dict[str, Any]:
    """Add new nodes and/or edges. Auto-generates IDs if not provided.

    ``resolves_pending`` is the list of pending-plan node ids this append
    *replaces*. A plan node is a temporary placeholder for intended work
    (carries ``metadata.pending_plan == true``); once you execute the plan
    and land the real ``result`` / ``decision`` node, the plan node has done
    its job and must disappear — the Draft records what *happened*, not what
    was *intended*. Pass the plan id(s) here and they are removed in the SAME
    atomic write that lands the result, so the graph never accumulates zombie
    "verified question" nodes. Safety: only nodes whose
    ``metadata.pending_plan`` is true are eligible for removal; any other id
    is ignored (logged), so this can never delete a real landed imprint.
    """
    port = _env_port()
    ts = _now_iso()
    
    # Create nodes using extracted function
    created_node_ids: list[str] = []
    if nodes:
        created_node_ids = create_nodes(port, nodes, ts)
    
    # Create edges using extracted function
    created_edge_count = 0
    if edges:
        # Infer batch author from nodes (fallback for edges without explicit author)
        batch_author = _env_role()
        if not batch_author and nodes:
            for node in nodes:
                if node.get("author_role"):
                    batch_author = node["author_role"]
                    break
        created_edge_count = create_edges(port, edges, ts, batch_author)
    
    # Resolve pending plans using extracted function
    resolved_plan_ids: list[str] = []
    if resolves_pending:
        resolved_plan_ids = resolve_pending_plans(port, resolves_pending, created_node_ids, ts)
    
    # Soft-audit: increment the per-role append counter
    if created_node_ids:
        try:
            from minions.tools import draft_audit as _draft_audit
            agent_id = os.environ.get("MINIONS_AGENT_ID", "") or _env_role()
            if agent_id:
                _draft_audit.record_append(port, agent_id, count=len(created_node_ids))
        except Exception as exc:
            logger.debug("draft_audit.record_append failed: %s", exc)
    
    return {
        "created_node_ids": created_node_ids,
        "created_edge_count": created_edge_count,
        "resolved_plan_ids": resolved_plan_ids,
    }


def mos_draft_annotate(
    node_id: str,
    support_status: DraftSupportStatus | None = None,
    evidence_tag: str | None = None,
    provenance: DraftProvenance | None = None,
    confidence: float | None = None,
    metadata_update: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Update an existing node's mutable fields. Type and text are immutable."""
    port = _env_port()
    draft = _load_draft(port)
    ts = _now_iso()

    target = None
    for node in draft["nodes"]:
        if node["id"] == node_id:
            target = node
            break
    if target is None:
        raise DraftError(f"Node not found: {node_id}")

    annotator = _env_role() or target.get("author_role", "")
    changes: dict[str, Any] = {}

    if support_status is not None:
        if support_status not in SUPPORT_STATUSES:
            logger.info("Custom support_status: %s", support_status)
        old = target.get("support_status", "")
        target["support_status"] = support_status
        changes["support_status"] = {"old": old, "new": support_status}
        append_journal(
            port,
            {
                "op": "annotate",
                "node_id": node_id,
                "field": "support_status",
                "old_value": old,
                "new_value": support_status,
                "evidence_tag": evidence_tag or "",
                "timestamp": ts,
                "author_role": annotator,
            },
        )

    if evidence_tag is not None:
        old = target.get("evidence_tag", "")
        target["evidence_tag"] = evidence_tag
        changes["evidence_tag"] = {"old": old, "new": evidence_tag}
        append_journal(
            port,
            {
                "op": "annotate",
                "node_id": node_id,
                "field": "evidence_tag",
                "old_value": old,
                "new_value": evidence_tag,
                "timestamp": ts,
                "author_role": annotator,
            },
        )

    if provenance is not None:
        if provenance not in PROVENANCES:
            logger.info("Custom provenance: %s (not in suggested provenances)", provenance)
        old = target.get("provenance")
        target["provenance"] = provenance
        changes["provenance"] = {"old": old, "new": provenance}
        append_journal(
            port,
            {
                "op": "annotate",
                "node_id": node_id,
                "field": "provenance",
                "old_value": old,
                "new_value": provenance,
                "timestamp": ts,
                "author_role": annotator,
            },
        )

    if confidence is not None:
        new_confidence = _validate_confidence(confidence)
        old = target.get("confidence")
        target["confidence"] = new_confidence
        changes["confidence"] = {"old": old, "new": new_confidence}
        append_journal(
            port,
            {
                "op": "annotate",
                "node_id": node_id,
                "field": "confidence",
                "old_value": old,
                "new_value": new_confidence,
                "timestamp": ts,
                "author_role": annotator,
            },
        )

    if metadata_update:
        old_meta = dict(target.get("metadata", {}))
        target.setdefault("metadata", {}).update(metadata_update)
        changes["metadata"] = {"added_keys": list(metadata_update.keys())}
        append_journal(
            port,
            {
                "op": "annotate",
                "node_id": node_id,
                "field": "metadata",
                "old_value": old_meta,
                "new_value": target["metadata"],
                "timestamp": ts,
                "author_role": annotator,
            },
        )

    _save_draft(port, draft)
    if support_status is not None and support_status in BOOK_STATUS_HOOK_STATUSES:
        token = _BOOK_STATUS_EVENT_TARGET.set(target)
        try:
            _emit_book_status_event(port, target["id"], support_status, annotator)
        except Exception as exc:
            logger.warning(
                "book status hook failed for node %s status %s: %s",
                target["id"],
                support_status,
                exc,
            )
        finally:
            _BOOK_STATUS_EVENT_TARGET.reset(token)
    return {"node_id": node_id, "changes": changes}





def mos_draft_summary() -> dict[str, Any]:
    """High-level Draft summary for role wakeup injection. Kept under 800 tokens.

    Surfaces pending plans (nodes with metadata.pending_plan == true) at the
    top so a freshly respawned post-reset agent can see what its previous
    self had planned but not yet executed, and pick up without losing work.
    """
    port = _env_port()
    draft = _load_draft(port)
    nodes = draft["nodes"]
    edges = draft["edges"]

    # Counts by type.
    by_type: dict[str, int] = defaultdict(int)
    for n in nodes:
        by_type[n.get("type", "unknown")] += 1

    # Counts by status.
    by_status: dict[str, int] = defaultdict(int)
    for n in nodes:
        by_status[n.get("support_status", "unknown")] += 1

    # Counts by provenance, including legacy nodes missing the field.
    by_provenance: dict[str, int] = defaultdict(int)
    by_provenance_role: defaultdict[str, defaultdict[str, int]] = defaultdict(
        lambda: defaultdict(int)
    )
    for n in nodes:
        provenance = str(n.get("provenance") or "unknown")
        role = str(n.get("author_role") or "unknown")
        by_provenance[provenance] += 1
        by_provenance_role[role][provenance] += 1

    # Pending plans — checkpointed-but-not-executed work. Newest first so a
    # post-reset agent picks up the most recent intent.
    pending = [
        n
        for n in nodes
        if (n.get("metadata") or {}).get("pending_plan") is True
        and n.get("support_status") in ("unverified", "tentative")
    ]
    pending.sort(key=lambda n: n.get("created_at", ""), reverse=True)
    pending_view = [
        {
            "id": p["id"],
            "type": p.get("type", ""),
            "text": p.get("text", ""),
            "author_role": p.get("author_role", ""),
            "created_at": p.get("created_at", ""),
        }
        for p in pending[:10]
    ]

    # Active hypotheses (tentative or unverified).
    active_hyps = [
        n
        for n in nodes
        if n.get("type") == "hypothesis" and n.get("support_status") in ("tentative", "unverified")
    ]

    # Recent decisions (last 5).
    decisions = [n for n in nodes if n.get("type") == "decision"]
    recent_decisions = sorted(decisions, key=lambda n: n.get("created_at", ""), reverse=True)[:5]

    # Blocked paths.
    blocked = [n for n in nodes if n.get("support_status") == "blocked"]

    # Dead ends.
    dead_ends = [n for n in nodes if n.get("type") == "dead_end"]

    # Decay sidecar (computed by Ethics via mos_draft_decay_compute).
    # Surfaces the most-decayed and most-reinforced nodes so a waking role
    # sees which prior knowledge has weakened or strengthened. Absent until
    # Ethics runs once — degrades cleanly to {} otherwise.
    decay_map = _load_decay(port)
    decay_view: dict[str, Any] = {}
    if decay_map:
        ranked = [
            (nid, entry)
            for nid, entry in decay_map.items()
            if isinstance(entry, dict) and "effective_confidence" in entry
        ]
        ranked.sort(key=lambda item: float(item[1].get("effective_confidence", 0.0)))
        most_decayed = [
            {
                "id": nid,
                "effective_confidence": entry.get("effective_confidence"),
                "stored_confidence": entry.get("stored_confidence"),
                "age_days": entry.get("age_days"),
                "supports": entry.get("supports"),
                "contradicts": entry.get("contradicts"),
            }
            for nid, entry in ranked[:5]
        ]
        ranked.sort(
            key=lambda item: float(item[1].get("effective_confidence", 0.0)),
            reverse=True,
        )
        most_reinforced = [
            {
                "id": nid,
                "effective_confidence": entry.get("effective_confidence"),
                "stored_confidence": entry.get("stored_confidence"),
                "supports": entry.get("supports"),
            }
            for nid, entry in ranked[:5]
            if int(entry.get("supports", 0) or 0) > 0
        ]
        decay_view = {
            "node_count": len(decay_map),
            "most_decayed": most_decayed,
            "most_reinforced": most_reinforced,
        }

    return {
        "project_port": port,
        "root_question": draft.get("root_question", ""),
        "total_nodes": len(nodes),
        "total_edges": len(edges),
        "pending_plans": pending_view,
        "pending_plans_total": len(pending),
        "nodes_by_type": dict(by_type),
        "nodes_by_status": dict(by_status),
        "nodes_by_provenance": dict(by_provenance),
        "nodes_by_provenance_role": {
            role: dict(counts) for role, counts in by_provenance_role.items()
        },
        "active_hypotheses": [{"id": h["id"], "text": h["text"]} for h in active_hyps[:10]],
        "recent_decisions": [{"id": d["id"], "text": d["text"]} for d in recent_decisions],
        "blocked_count": len(blocked),
        "dead_end_count": len(dead_ends),
        "decay": decay_view,
    }




def mos_draft_view(
    query: str | None = None,
    by_role: str | None = None,
    by_status: DraftSupportStatus | None = None,
    by_type: DraftNodeType | None = None,
    related_to: str | None = None,
    sort: str = "time",
    limit: int = 20,
) -> dict[str, Any]:
    """The single unified read over the Draft graph for role agents.

    One tool, orthogonal dimensions. It always returns a compact orientation
    header (totals, pending_plans, counts) so a waking role gets its bearings
    in one call, plus the requested slice of nodes and their incident edges.

    Dimensions (combine freely; all optional):
      - query: free-text relevance push (keyword overlap + type weighting).
      - by_role / by_status / by_type: exact-match filters.
      - related_to: 1-hop neighbour subgraph of a node id (ignores filters).
      - sort: "time" (newest landed first — the default a waking role wants),
        "relevance" (only meaningful with query), or "confidence".
      - limit: max nodes in the slice.

    This subsumes the older summary / query / relevant / topic_index reads:
    call with no args for the orientation header + newest nodes (cold-start
    orient); pass query for relevance; pass related_to for a neighbourhood.
    """
    port = _env_port()
    header = mos_draft_summary()  # orientation: totals, pending_plans, counts, decay

    # Slice selection.
    if related_to:
        sub = mos_draft_query(related_to=related_to, limit=limit)
        nodes = list(sub["nodes"])
        edges = list(sub["edges"])
    elif query:
        rel = mos_draft_relevant(query, max_nodes=limit)
        nodes = list(rel["relevant_nodes"])
        edges = list(rel["relevant_edges"])
    else:
        sub = mos_draft_query(
            node_type=by_type,
            support_status=by_status,
            author_role=by_role,
            limit=max(limit * 4, limit),  # over-fetch; re-sort + trim below
        )
        nodes = list(sub["nodes"])
        edges = list(sub["edges"])

    # Apply remaining filters that the chosen slice did not already enforce
    # (query/related_to paths ignore the exact-match filters, so honour them here).
    if by_role:
        nodes = [n for n in nodes if (n.get("author_role") or "") == by_role]
    if by_status:
        nodes = [n for n in nodes if n.get("support_status") == by_status]
    if by_type:
        nodes = [n for n in nodes if n.get("type") == by_type]

    # Sort. "relevance" keeps mos_draft_relevant's order; time/confidence re-sort.
    if sort == "time":
        nodes.sort(key=lambda n: n.get("created_at", ""), reverse=True)
    elif sort == "confidence":
        nodes.sort(key=lambda n: float(n.get("confidence", 0.0) or 0.0), reverse=True)

    nodes = nodes[:limit]
    node_ids = {n["id"] for n in nodes}
    edges = [e for e in edges if e["from_id"] in node_ids or e["to_id"] in node_ids]

    return {
        "project_port": port,
        "root_question": header.get("root_question", ""),
        "totals": {
            "nodes": header.get("total_nodes", 0),
            "edges": header.get("total_edges", 0),
        },
        "pending_plans": header.get("pending_plans", []),
        "pending_plans_total": header.get("pending_plans_total", 0),
        "nodes_by_type": header.get("nodes_by_type", {}),
        "nodes_by_status": header.get("nodes_by_status", {}),
        "filter": {
            "query": query,
            "by_role": by_role,
            "by_status": by_status,
            "by_type": by_type,
            "related_to": related_to,
            "sort": sort,
        },
        "nodes": nodes,
        "edges": edges,
        "returned": len(nodes),
    }



def mos_draft_commit_shared(message: str | None = None) -> dict[str, Any]:
    """Flush the buffered Draft to a single commit on the shared branch.

    Owned by Ethics. The Draft file at
    ``branches/main/draft/draft.json`` is updated freely by every
    role through ``mos_draft_append`` / ``mos_draft_annotate`` (working tree
    only, no commit). This tool performs one auditable commit per call by
    publishing the current Draft state through ``mos_publish_to_shared``.

    Intended use: Ethics cron tick (default every 5 minutes — configurable
    in ``gru.yaml``). Other roles must not call this themselves; the
    whitelist binds it to Ethics and Gru only.

    Returns the publish result dict (``commit_sha``, ``branch``, etc.).
    Raises if the Draft file does not exist or the publish fails.
    """
    from minions.tools.publish import mos_publish_to_shared

    port = _env_port()
    draft_path = _draft_path(port)
    if not draft_path.exists():
        return {
            "port": port,
            "role": _env_role() or "ethics",
            "dst_path": "draft/draft.json",
            "commit_sha": None,
            "pushed": False,
            "push_branch": None,
            "branch": None,
            "skipped": "draft.json does not exist yet",
        }
    msg = message or f"ethics: draft flush {_now_iso()}"
    # mos_publish_to_shared returns a PublishToSharedResult (DictLikeBaseModel)
    # which is read-compatible with dict[str, Any] via __getitem__/get. Cast
    # preserves the existing tool contract while keeping the typed return
    # at the publish layer.
    return cast(
        "dict[str, Any]",
        mos_publish_to_shared(
            role=_env_role() or "ethics",
            src_path=str(draft_path),
            dst_subpath="draft/draft.json",
            commit_message=msg,
            port=port,
        ),
    )


def mos_draft_relevant(context_text: str, max_nodes: int = 10) -> dict[str, Any]:
    """Find Draft nodes relevant to a given context (event text, task description).

    This is the PUSH mechanism: instead of the agent deciding what to query,
    the system finds relevant prior knowledge based on what the agent is
    currently looking at.

    Uses keyword overlap between context_text and node text/metadata.
    No vector embeddings needed — simple but effective for structured nodes.
    """
    port = _env_port()
    dag_data = _load_draft(port)
    nodes = dag_data["nodes"]
    edges = dag_data["edges"]

    if not nodes or not context_text:
        return {"relevant_nodes": [], "relevant_edges": []}

    # Build searchable text per node (text + type + metadata values)
    context_lower = context_text.lower()
    context_words = {w for w in context_lower.split() if len(w) > 3}

    scored: list[tuple[float, dict]] = []
    for node in nodes:
        # Combine all searchable fields
        parts = [
            node.get("text", ""),
            node.get("type", ""),
            node.get("id", ""),
        ]
        # Include metadata values (topic, reason, etc.)
        meta = node.get("metadata", {})
        if isinstance(meta, dict):
            parts.extend(str(v) for v in meta.values())
        node_searchable = " ".join(parts).lower()
        node_words = {w for w in node_searchable.split() if len(w) > 3}

        # Score: keyword overlap + substring containment
        overlap = len(context_words & node_words)
        # Also check if any context word is a substring of node text
        for cw in context_words:
            if cw in node_searchable and cw not in node_words:
                overlap += 0.5

        if overlap > 0:
            boost = 1.0
            if node.get("type") == "dead_end":
                boost = 2.0
            elif node.get("type") == "decision":
                boost = 1.5
            elif node.get("support_status") == "verified":
                boost = 1.3
            scored.append((overlap * boost, node))

    # Sort by relevance, take top N
    scored.sort(key=lambda x: x[0], reverse=True)
    relevant_nodes = [node for _, node in scored[:max_nodes]]

    # Get edges connecting relevant nodes
    relevant_ids = {n["id"] for n in relevant_nodes}
    relevant_edges = [
        e for e in edges if e["from_id"] in relevant_ids or e["to_id"] in relevant_ids
    ]

    # Fallback: if no keyword matches, return top-level nodes as orientation
    if not scored:
        # Return hypotheses, decisions, insights as general orientation
        fallback = [
            n for n in nodes if n.get("type") in ("hypothesis", "decision", "insight", "result")
        ]
        fallback.sort(key=lambda n: n.get("created_at", ""), reverse=True)
        relevant_nodes = fallback[:max_nodes]
        relevant_ids = {n["id"] for n in relevant_nodes}
        relevant_edges = [
            e for e in edges if e["from_id"] in relevant_ids or e["to_id"] in relevant_ids
        ]
        return {
            "relevant_nodes": relevant_nodes,
            "relevant_edges": relevant_edges,
            "match_count": len(fallback),
            "fallback": True,
        }

    return {
        "relevant_nodes": relevant_nodes,
        "relevant_edges": relevant_edges,
        "match_count": len(scored),
    }


def mos_draft_topic_index() -> dict[str, Any]:
    """Return a topic-level index of the Draft.

    Groups nodes by their metadata 'topic' field (if present) or by
    community membership. Provides a one-line orientation per topic
    so agents know what prior work exists without querying each topic.
    """
    port = _env_port()
    dag_data = _load_draft(port)
    nodes = dag_data["nodes"]

    # Group by topic metadata
    topics: dict[str, list[dict]] = {}
    for node in nodes:
        topic = node.get("metadata", {}).get("topic", "")
        if not topic:
            # Infer topic from first significant word in text
            words = node.get("text", "").lower().split()
            topic = next((w for w in words if len(w) > 4), "general")
        topics.setdefault(topic, []).append(node)

    # Build index
    index = []
    for topic, topic_nodes in sorted(topics.items(), key=lambda x: -len(x[1])):
        statuses = {}
        for n in topic_nodes:
            s = n.get("support_status", "unverified")
            statuses[s] = statuses.get(s, 0) + 1
        dead_ends = sum(1 for n in topic_nodes if n.get("type") == "dead_end")
        latest = max(topic_nodes, key=lambda n: n.get("created_at", ""))
        index.append(
            {
                "topic": topic,
                "node_count": len(topic_nodes),
                "latest_node": latest["id"],
                "status_summary": statuses,
                "dead_ends": dead_ends,
            }
        )

    return {"topics": index, "total_topics": len(index)}


def mos_draft_communities() -> dict[str, Any]:
    """Detect communities using connected components + label propagation.

    Phase 1: Find connected components (handles disconnected subgraphs).
    Phase 2: Within large components (>10 nodes), use label propagation
             to find sub-communities.

    Returns clusters of related nodes that form coherent research threads.
    """
    port = _env_port()
    dag_data = _load_draft(port)
    nodes = dag_data["nodes"]
    edges = dag_data["edges"]

    if not nodes:
        return {"communities": [], "total_communities": 0, "cross_community_edges": []}

    node_ids = {n["id"] for n in nodes}
    nodes_by_id = {n["id"]: n for n in nodes}

    # Build undirected adjacency.
    adj: dict[str, list[str]] = defaultdict(list)
    for edge in edges:
        if edge["from_id"] in node_ids and edge["to_id"] in node_ids:
            adj[edge["from_id"]].append(edge["to_id"])
            adj[edge["to_id"]].append(edge["from_id"])

    # Phase 1: Connected components via BFS.
    visited: set[str] = set()
    components: list[set[str]] = []
    for nid in node_ids:
        if nid in visited:
            continue
        # BFS from this node
        component: set[str] = set()
        queue = deque([nid])
        while queue:
            curr = queue.popleft()
            if curr in visited:
                continue
            visited.add(curr)
            component.add(curr)
            for nb in adj.get(curr, []):
                if nb not in visited and nb in node_ids:
                    queue.append(nb)
        components.append(component)

    # Phase 2: For large components, sub-divide with label propagation.
    final_groups: list[list[str]] = []
    for comp in components:
        if len(comp) <= 10:
            final_groups.append(list(comp))
            continue
        # Label propagation within this component
        labels = {nid: nid for nid in comp}
        for _ in range(50):
            changed = False
            order = list(comp)
            random.shuffle(order)
            for nid in order:
                neighbors = [nb for nb in adj.get(nid, []) if nb in comp]
                if not neighbors:
                    continue
                counts: dict[str, int] = defaultdict(int)
                for nb in neighbors:
                    counts[labels[nb]] += 1
                if not counts:
                    continue
                max_count = max(counts.values())
                candidates = [lbl for lbl, c in counts.items() if c == max_count]
                best = min(candidates)
                if labels[nid] != best:
                    labels[nid] = best
                    changed = True
            if not changed:
                break
        # Group by label within component
        sub_groups: dict[str, list[str]] = defaultdict(list)
        for nid, lbl in labels.items():
            sub_groups[lbl].append(nid)
        final_groups.extend(sub_groups.values())

    # Sort by size descending, assign IDs.
    final_groups.sort(key=len, reverse=True)
    node_to_community: dict[str, int] = {}
    communities_out = []
    for idx, group in enumerate(final_groups):
        for nid in group:
            node_to_community[nid] = idx
        # Determine dominant type
        type_counts: dict[str, int] = defaultdict(int)
        for nid in group:
            if nid in nodes_by_id:
                type_counts[nodes_by_id[nid].get("type", "unknown")] += 1
        dominant = max(type_counts, key=lambda k: type_counts[k]) if type_counts else "unknown"
        communities_out.append(
            {
                "id": idx,
                "size": len(group),
                "nodes": group,
                "dominant_type": dominant,
            }
        )

    # Cross-community edges.
    cross = []
    for edge in edges:
        f, t = edge["from_id"], edge["to_id"]
        if f in node_to_community and t in node_to_community:
            cf, ct = node_to_community[f], node_to_community[t]
            if cf != ct:
                cross.append(
                    {
                        "from": f,
                        "to": t,
                        "relation": edge.get("relation", ""),
                        "communities": [cf, ct],
                    }
                )

    return {
        "communities": communities_out,
        "total_communities": len(communities_out),
        "cross_community_edges": cross,
    }


def mos_draft_god_nodes(top_n: int = 5) -> dict[str, Any]:
    """Identify hub nodes with highest connectivity (degree centrality).

    These are foundational assumptions or key results that many other
    nodes depend on. Changing a god node affects the whole graph.
    """
    port = _env_port()
    draft = _load_draft(port)
    nodes = draft["nodes"]
    edges = draft["edges"]

    if not nodes:
        return {"god_nodes": []}

    nodes_by_id: dict[str, dict] = {n["id"]: n for n in nodes}
    type_of: dict[str, str] = {n["id"]: n.get("type", "unknown") for n in nodes}

    # Degree and cross-type connections.
    degree: dict[str, int] = defaultdict(int)
    connected_ids: dict[str, set[str]] = defaultdict(set)
    connected_types: dict[str, set[str]] = defaultdict(set)

    for edge in edges:
        fid, tid = edge["from_id"], edge["to_id"]
        degree[fid] += 1
        degree[tid] += 1
        connected_ids[fid].add(tid)
        connected_ids[tid].add(fid)
        connected_types[fid].add(type_of.get(tid, "unknown"))
        connected_types[tid].add(type_of.get(fid, "unknown"))

    # Score = degree * (1 + 0.2 * cross_type_count).
    scored: list[tuple[float, str]] = []
    for nid in nodes_by_id:
        d = degree.get(nid, 0)
        ct = len(connected_types.get(nid, set()))
        score = d * (1.0 + 0.2 * ct)
        scored.append((score, nid))

    scored.sort(key=lambda x: (-x[0], x[1]))
    top = scored[:top_n]

    god_nodes = []
    for score, nid in top:
        node = nodes_by_id[nid]
        god_nodes.append(
            {
                "id": nid,
                "text": node.get("text", ""),
                "score": round(score, 2),
                "degree": degree.get(nid, 0),
                "cross_type_connections": len(connected_types.get(nid, set())),
                "connected_to": sorted(connected_ids.get(nid, set())),
            }
        )

    return {"god_nodes": god_nodes}
